# Generated by Django 5.0.6 on 2025-09-12 07:32

import django.db.models.deletion
import finca.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finca', '0002_postsave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=finca.models.user_directory_path)),
                ('caption', models.TextField(blank=True)),
                ('bibliography', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finca_cover_slides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('user', 'index')},
            },
        ),
    ]
